/* Partial libmus channel layout (0x13C bytes) recovered from this ROM.
   Generated by tools/genhdr.py; padding names are offsets. */
typedef struct channel_s {
    unsigned int flags; /* 0x00 */
    unsigned char *pdata; /* 0x04 */
    void *f08; /* 0x08 */
    int f0C; /* 0x0C */
    int stopping; /* 0x10 */
    int f14; /* 0x14 */
    int f18; /* 0x18 */
    int stopping_speed; /* 0x1C */
    float f20; /* 0x20 */
    float f24; /* 0x24 */
    float f28; /* 0x28 */
    float f2C; /* 0x2C */
    float freqoffset; /* 0x30 */
    unsigned char *f34; /* 0x34 */
    unsigned char *f38; /* 0x38 */
    int f3C; /* 0x3C */
    int f40; /* 0x40 */
    int handle; /* 0x44 */
    int f48; /* 0x48 */
    float f4C; /* 0x4C */
    float f50; /* 0x50 */
    int f54; /* 0x54 */
    float f58; /* 0x58 */
    float f5C; /* 0x5C */
    float f60; /* 0x60 */
    int f64; /* 0x64 */
    float f68; /* 0x68 */
    float f6C; /* 0x6C */
    float f70; /* 0x70 */
    void *song_bank; /* 0x74 */
    void *sample_bank; /* 0x78 */
    void *f7C; /* 0x7C */
    unsigned char *f80; /* 0x80 */
    void *f84; /* 0x84 */
    unsigned char *f88; /* 0x88 */
    unsigned char *f8C; /* 0x8C */
    float base_freq; /* 0x90 */
    int f94; /* 0x94 */
    short volume_scale; /* 0x98 */
    unsigned short f9A; /* 0x9A */
    unsigned short volume; /* 0x9C */
    short temscale; /* 0x9E */
    unsigned short fA0; /* 0xA0 */
    unsigned short fA2; /* 0xA2 */
    unsigned short fA4; /* 0xA4 */
    unsigned short fx_number; /* 0xA6 */
    unsigned short base_volume; /* 0xA8 */
    unsigned short fAA; /* 0xAA */
    unsigned short fAC; /* 0xAC */
    unsigned short fAE; /* 0xAE */
    short pan_scale; /* 0xB0 */
    unsigned short fB2; /* 0xB2 */
    unsigned short fB4; /* 0xB4 */
    unsigned char fB6; /* 0xB6 */
    unsigned char fB7; /* 0xB7 */
    unsigned char fB8; /* 0xB8 */
    unsigned char fB9; /* 0xB9 */
    unsigned char fBA; /* 0xBA */
    unsigned char fBB; /* 0xBB */
    unsigned char fBC; /* 0xBC */
    unsigned char fBD; /* 0xBD */
    unsigned char pan_changed; /* 0xBE */
    unsigned char fBF; /* 0xBF */
    unsigned char fC0; /* 0xC0 */
    unsigned char fC1; /* 0xC1 */
    unsigned char fC2; /* 0xC2 */
    unsigned char fC3; /* 0xC3 */
    unsigned char fC4; /* 0xC4 */
    unsigned char fC5; /* 0xC5 */
    unsigned char fC6; /* 0xC6 */
    unsigned char fC7; /* 0xC7 */
    unsigned char fC8; /* 0xC8 */
    unsigned char fC9; /* 0xC9 */
    unsigned char fCA; /* 0xCA */
    unsigned char pan; /* 0xCB */
    unsigned char pan_dirty; /* 0xCC */
    unsigned char fCD; /* 0xCD */
    unsigned char fCE; /* 0xCE */
    unsigned char fCF; /* 0xCF */
    unsigned char fD0; /* 0xD0 */
    signed char fD1; /* 0xD1 */
    unsigned char fD2; /* 0xD2 */
    unsigned char fD3; /* 0xD3 */
    unsigned char fD4; /* 0xD4 */
    unsigned char fD5; /* 0xD5 */
    unsigned char fD6; /* 0xD6 */
    unsigned char fD7; /* 0xD7 */
    unsigned char fD8; /* 0xD8 */
    unsigned char fD9; /* 0xD9 */
    unsigned char fDA; /* 0xDA */
    unsigned char fDB; /* 0xDB */
    float fDC; /* 0xDC */
    unsigned char *fE0[4]; /* 0xE0 */
    unsigned char *fF0[4]; /* 0xF0 */
    unsigned char *f100[4]; /* 0x100 */
    unsigned short f110[4]; /* 0x110 */
    unsigned short f118[4]; /* 0x118 */
    unsigned char f120[4]; /* 0x120 */
    unsigned char f124[4]; /* 0x124 */
    float f128[4]; /* 0x128 */
    unsigned char pad138[0x4];
} channel_t;

extern int D_803AD974;           /* max_channels */
extern channel_t *D_803AD97C;    /* mus_channels */
